# coding: utf-8

# flake8: noqa
"""
    Task Management API

    API cho việc quản lý các nhiệm vụ trong ngày

    The version of the OpenAPI document: 1.0.0
    Contact: anhtoan07112002@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.task import Task
