# Generated by Django 5.1.4 on 2024-12-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'chưa thực hiện'), ('IN_PROGRESS', 'đang tiến hành'), ('COMPLETED', 'đã hoàn thành'), ('OVERDUE', 'quá hạn')], default='PENDING', max_length=25),
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('notify_type', models.CharField(choices=[('START_SOON', 'Task sắp đến giờ bắt đầu'), ('END_SOON', 'Task sắp kết thúc')], max_length=20)),
                ('is_readed', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifys', to='todoListApp.task')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
